volumes:
  open_webui_storage:
  ollama_storage:

x-open-webui: &service-open-webui
  image: ghcr.io/open-webui/open-webui:latest
  network_mode: host
  environment:
    - OLLAMA_BASE_URL=http://127.0.0.1:11434
  volumes:
    - open_webui_storage:/app/backend/data

x-ollama: &service-ollama
  image: ollama/ollama:latest
  container_name: ollama
  network_mode: host
  volumes:
    - ollama_storage:/root/.ollama

x-init-ollama: &init-ollama
  image: ollama/ollama:latest
  network_mode: host
  container_name: ollama-pull-llama
  volumes:
    - ollama_storage:/root/.ollama
  entrypoint: /bin/sh
  command:
    - "-c"
    - "sleep 3; OLLAMA_HOST=127.0.0.1:11434 ollama pull deepseek-r1:7b"

services:
  open-webui:
    <<: *service-open-webui
    container_name: open-webui
    restart: unless-stopped

  ollama-cpu:
    profiles: ["cpu"]
    <<: *service-ollama

  ollama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *service-ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-pull-llama-cpu:
    profiles: ["cpu"]
    <<: *init-ollama
    depends_on:
      - ollama-cpu

  ollama-pull-llama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *init-ollama
    depends_on:
      - ollama-gpu
